import { Injectable, Logger, OnModuleDestroy } from '@nestjs/common';
import puppeteer, { Browser } from 'puppeteer';
import { readFileSync } from 'node:fs';
import * as path from 'node:path';
import { marked } from 'marked';

@Injectable()
export class PuppeteerService implements OnModuleDestroy {
  private readonly log = new Logger(PuppeteerService.name);
  private browser: Browser | null = null;
  private readonly css = readFileSync(path.join(__dirname, 'report-template.css'), 'utf8');

  async renderMarkdown(md: string, fallbackTitle: string): Promise<Buffer> {
    // Escape stray single tildes so "~80%" doesn't get strikethrough'd by GFM.
    const mdSafe = md.replace(/(?<!~)~(?!~)/g, '\\~');
    const titleMatch = md.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1].trim() : fallbackTitle;
    const today = new Date().toLocaleDateString('en-GB', {
      year: 'numeric',
      month: 'long',
      day: '2-digit',
    });
    const bodyHtml = await marked.parse(mdSafe);

    const html = `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>${this.css}</style></head>
<body>
  <header class="cover">
    <div class="eyebrow">Personal Portfolio · Monthly Report</div>
    <h1 class="title">${escapeHtml(title)}</h1>
    <div class="meta">Prepared <strong>${escapeHtml(today)}</strong></div>
  </header>
  <main>${bodyHtml}</main>
  <p class="disclaimer">Personal investment notes generated by an automated advisor prompt. Not financial advice. Verify all figures and account details before acting. Past performance does not guarantee future results.</p>
</body></html>`;

    const browser = await this.getBrowser();
    const page = await browser.newPage();
    try {
      await page.setContent(html, { waitUntil: 'networkidle0' });
      const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '22mm', bottom: '24mm', left: '18mm', right: '18mm' },
        displayHeaderFooter: true,
        headerTemplate: `<div style="font-family:Georgia,serif;font-size:9px;color:#6b7280;width:100%;padding:0 18mm;display:flex;justify-content:space-between;border-bottom:0.4pt solid #c7a44a;padding-bottom:4pt;"><span class="title"></span><span>Confidential — Personal</span></div>`,
        footerTemplate: `<div style="font-family:Georgia,serif;font-size:8.5px;color:#6b7280;width:100%;padding:0 18mm;display:flex;justify-content:space-between;"><span>Generated ${escapeHtml(today)}</span><span>Page <span class="pageNumber"></span> of <span class="totalPages"></span></span></div>`,
      });
      return Buffer.from(pdf);
    } finally {
      await page.close().catch(() => undefined);
    }
  }

  private async getBrowser(): Promise<Browser> {
    if (this.browser?.connected) return this.browser;
    this.browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });
    return this.browser;
  }

  async onModuleDestroy(): Promise<void> {
    await this.browser?.close().catch(() => undefined);
  }
}

function escapeHtml(s: string): string {
  return s.replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c] as string,
  );
}
